name: trigger-jenkins-build
run-name: Trigger jenkins build
on:
  pull_request:
    branches:
      - main
    # types: [closed]
jobs:
  trigget-jenkins-build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    - name: "Trigger jenkins job"
      uses: GoldenspearLLC/build-jenkins-job@master
      with:
        jenkins-url: "http://180.229.230.102:8080/"
        jenkins-token: ${{ secrets.JYHUR_JENKINS_TOKEN }}
        user: "jenkins-username"
        job-path: "job/jenkins_test/job/main/"
        job-params: ""
    - name: Get job status
      run: echo "Job status is ${{ steps.job-build.outputs.job_status }}"


